on: 
  push:
    branches:
      - master

name: Master

jobs:

  web:
    name: Web Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js v14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Check Version
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install AWS CLI
        uses: chrislennon/action-aws-cli@v1.1
        if: steps.check.outputs.changed == 'true'

      - name: Set Secrets
        if: steps.check.outputs.changed == 'true'
        env:
          NPMRC: ${{ secrets.NPMRC }}
        run: |
          echo "$NPMRC" >> .npmrc

      - name: Install Dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: npm run web:build

      - name: Publish to S3
        if: steps.check.outputs.changed == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: node ./.scripts/s3Push.js

      - name: Create Release
        uses: actions/create-release@v1
        if: steps.check.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.check.outputs.version }}
          release_name: Release v${{ steps.check.outputs.version }}

  android:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js v14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Check Version
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        if: steps.check.outputs.changed == 'true'
        with:
          java-version: 1.8

      - name: Setup MIPS build process
        if: steps.check.outputs.changed == 'true'
        run: sudo mkdir -p $ANDROID_HOME/ndk-bundle/toolchains/mips64el-linux-android/prebuilt/darwin-x86_64

      - name: Set Secrets
        if: steps.check.outputs.changed == 'true'
        env:
          NPMRC: ${{ secrets.NPMRC }}
          CORDOVA_BUILD: ${{ secrets.CORDOVA_BUILD }}
          CORDOVA_KEYSTORE: ${{ secrets.CORDOVA_KEYSTORE }}
        run: |
          echo "$NPMRC" >> .npmrc
          echo "$CORDOVA_BUILD" >> ./src-cordova/build.json
          echo "$CORDOVA_KEYSTORE" >> ./src-cordova/prod.keystore

      - name: Install Dependencies
        if: steps.check.outputs.changed == 'true'
        run: |
          npm ci
          npm install -g cordova@9

      - name: Prepare Cordova
        if: steps.check.outputs.changed == 'true'
        run: npm run cordova:prepare

      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: npm run android:build

      - name: Publish to Google Play
        uses: r0adkll/upload-google-play@v1
        if: steps.check.outputs.changed == 'true'
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.zachcardoza.gcc.awana
          releaseFile: 'src-cordova/platforms/android/app/build/outputs/apk/release/app-release.apk'
          track: beta